### ISSUE TITLE
accept_hostkey=yes

### ISSUE THREAD

**Issue by rommsen** [f500/ansible-project_deploy#12]
Hi,

are you open to add the accept_hostkey option to the git task?
e.g.   
```yaml
git: "repo={{ project_git_repo }} dest={{ project_source_path }} version={{ project_version }} accept_hostkey={{ project_git_accept_hostkey }}"
```

**Comment by ramondelafuente** [comment]
It would push the mimimum Ansible requirement to 1.5, but I think that's acceptable... I'll look into actual release dates a bit closer.

I do feel that accepting the hostkey without verification is on the dangerous side for a deploy role, as it opens the door to man-in-the-middle attacks that you would never know about. Not adding this option at lease forces the consumers to use some other avenue to add the github (or any VCS source server) hostkey.

**Comment by rommsen** [comment]
Allright. I was expecting something like this. Then we will have to add the hostkey by hand.

Ping me if you changed your mind. I'll prepare a PR then.

**Comment by ramondelafuente** [comment]
I've used this in the past (also the same security risk, but because the 'lookup' plugin runs on the host machine, the MIM would have to target both my current location and the server I'm deploying to at the same time).

https://coderwall.com/p/wi8yrq/ansible-lineinfile-with-lookup

**Comment by rommsen** [comment]
Thanks!

**Comment by ramondelafuente** [comment]
Decided agains adding the `accept_hostkey` option, because it makes 'doing it wrong' too easy.

**Comment by William-Yeh** [comment]
@rommsen I use the [bfmartin.ssh_known_hosts](https://galaxy.ansible.com/list#/roles/1456) role to allow github.com access:

```
roles:
    - { role: bfmartin.ssh_known_hosts, host: github.com }
```
