### ISSUE TITLE
ansible galaxy page not found

### ISSUE THREAD

**Issue by Incanus3** [f500/ansible-project_deploy#35]
Hi,
I don't know, how this can happen, but even though I can find the role on ansible galaxy (it shows up in the list), when I try to proceed to the [role page](https://galaxy.ansible.com/f500/project_deploy), I'm getting "page not found".

**Comment by ramondelafuente** [comment]
I have the same in the admin panel... not sure why. See https://github.com/ansible/galaxy/issues/2237
